-- VHDL netlist generated by SCUBA Diamond (64-bit) 3.10.0.111.2
-- Module  Version: 5.8
--/usr/local/diamond/3.10_x64/ispfpga/bin/lin64/scuba -w -n async_fifo -lang vhdl -synth synplify -bus_exp 7 -bb -arch xo2c00 -type ebfifo -depth 2048 -width 32 -rwidth 32 -no_enable -pe 512 -pf 1536 

-- Fri Aug  9 05:00:18 2019

library IEEE;
use IEEE.std_logic_1164.all;
-- synopsys translate_off
library MACHXO2;
use MACHXO2.components.all;
-- synopsys translate_on

entity async_fifo is
    port (
        data: in  std_logic_vector(31 downto 0); 
        wr_clock: in  std_logic; 
        rd_clock: in  std_logic; 
        wr_en: in  std_logic; 
        rd_en: in  std_logic; 
        reset: in  std_logic; 
        rpreset: in  std_logic; 
        q: out  std_logic_vector(31 downto 0); 
        empty: out  std_logic; 
        full: out  std_logic; 
        almost_empty: out  std_logic; 
        almost_full: out  std_logic);
end async_fifo;

architecture Structure of async_fifo is

    -- internal signal declarations
    signal scuba_vhi: std_logic;
    signal empty_int: std_logic;
    signal full_int: std_logic;
    signal scuba_vlo: std_logic;

    -- local component declarations
    component VHI
        port (Z: out  std_logic);
    end component;
    component VLO
        port (Z: out  std_logic);
    end component;
    component FIFO8KB
        generic (FULLPOINTER1 : in String; FULLPOINTER : in String; 
                AFPOINTER1 : in String; AFPOINTER : in String; 
                AEPOINTER1 : in String; AEPOINTER : in String; 
                ASYNC_RESET_RELEASE : in String; RESETMODE : in String; 
                GSR : in String; CSDECODE_R : in String; 
                CSDECODE_W : in String; REGMODE : in String; 
                DATA_WIDTH_R : in Integer; DATA_WIDTH_W : in Integer);
        port (DI0: in  std_logic; DI1: in  std_logic; DI2: in  std_logic; 
            DI3: in  std_logic; DI4: in  std_logic; DI5: in  std_logic; 
            DI6: in  std_logic; DI7: in  std_logic; DI8: in  std_logic; 
            DI9: in  std_logic; DI10: in  std_logic; DI11: in  std_logic; 
            DI12: in  std_logic; DI13: in  std_logic; 
            DI14: in  std_logic; DI15: in  std_logic; 
            DI16: in  std_logic; DI17: in  std_logic; 
            CSW0: in  std_logic; CSW1: in  std_logic; 
            CSR0: in  std_logic; CSR1: in  std_logic; 
            FULLI: in  std_logic; EMPTYI: in  std_logic; 
            WE: in  std_logic; RE: in  std_logic; ORE: in  std_logic; 
            CLKW: in  std_logic; CLKR: in  std_logic; RST: in  std_logic; 
            RPRST: in  std_logic; DO0: out  std_logic; 
            DO1: out  std_logic; DO2: out  std_logic; 
            DO3: out  std_logic; DO4: out  std_logic; 
            DO5: out  std_logic; DO6: out  std_logic; 
            DO7: out  std_logic; DO8: out  std_logic; 
            DO9: out  std_logic; DO10: out  std_logic; 
            DO11: out  std_logic; DO12: out  std_logic; 
            DO13: out  std_logic; DO14: out  std_logic; 
            DO15: out  std_logic; DO16: out  std_logic; 
            DO17: out  std_logic; EF: out  std_logic; 
            AEF: out  std_logic; AFF: out  std_logic; FF: out  std_logic);
    end component;
    attribute syn_keep : boolean;
    attribute NGD_DRC_MASK : integer;
    attribute NGD_DRC_MASK of Structure : architecture is 1;

begin
    -- component instantiation statements
    async_fifo_0_7: FIFO8KB
        generic map (FULLPOINTER1=> "0b01111111111100", FULLPOINTER=> "0b10000000000000", 
        AFPOINTER1=> "0b01011111111100", AFPOINTER=> "0b01100000000000", 
        AEPOINTER1=> "0b00100000000100", AEPOINTER=> "0b00100000000000", 
        ASYNC_RESET_RELEASE=> "SYNC", GSR=> "DISABLED", RESETMODE=> "ASYNC", 
        REGMODE=> "NOREG", CSDECODE_R=> "0b11", CSDECODE_W=> "0b11", 
        DATA_WIDTH_R=>  4, DATA_WIDTH_W=>  4)
        port map (DI0=>data(0), DI1=>data(1), DI2=>data(2), DI3=>data(3), 
            DI4=>scuba_vlo, DI5=>scuba_vlo, DI6=>scuba_vlo, 
            DI7=>scuba_vlo, DI8=>scuba_vlo, DI9=>scuba_vlo, 
            DI10=>scuba_vlo, DI11=>scuba_vlo, DI12=>scuba_vlo, 
            DI13=>scuba_vlo, DI14=>scuba_vlo, DI15=>scuba_vlo, 
            DI16=>scuba_vlo, DI17=>scuba_vlo, CSW0=>scuba_vhi, 
            CSW1=>scuba_vhi, CSR0=>scuba_vhi, CSR1=>scuba_vhi, 
            FULLI=>full_int, EMPTYI=>empty_int, WE=>wr_en, RE=>rd_en, 
            ORE=>rd_en, CLKW=>wr_clock, CLKR=>rd_clock, RST=>reset, 
            RPRST=>rpreset, DO0=>q(0), DO1=>q(1), DO2=>q(2), DO3=>q(3), 
            DO4=>open, DO5=>open, DO6=>open, DO7=>open, DO8=>open, 
            DO9=>open, DO10=>open, DO11=>open, DO12=>open, DO13=>open, 
            DO14=>open, DO15=>open, DO16=>open, DO17=>open, 
            EF=>empty_int, AEF=>almost_empty, AFF=>almost_full, 
            FF=>full_int);

    async_fifo_1_6: FIFO8KB
        generic map (FULLPOINTER1=> "0b00000000000000", FULLPOINTER=> "0b11111111111100", 
        AFPOINTER1=> "0b00000000000000", AFPOINTER=> "0b11111111111100", 
        AEPOINTER1=> "0b00000000000000", AEPOINTER=> "0b11111111111100", 
        ASYNC_RESET_RELEASE=> "SYNC", GSR=> "DISABLED", RESETMODE=> "ASYNC", 
        REGMODE=> "NOREG", CSDECODE_R=> "0b11", CSDECODE_W=> "0b11", 
        DATA_WIDTH_R=>  4, DATA_WIDTH_W=>  4)
        port map (DI0=>data(4), DI1=>data(5), DI2=>data(6), DI3=>data(7), 
            DI4=>scuba_vlo, DI5=>scuba_vlo, DI6=>scuba_vlo, 
            DI7=>scuba_vlo, DI8=>scuba_vlo, DI9=>scuba_vlo, 
            DI10=>scuba_vlo, DI11=>scuba_vlo, DI12=>scuba_vlo, 
            DI13=>scuba_vlo, DI14=>scuba_vlo, DI15=>scuba_vlo, 
            DI16=>scuba_vlo, DI17=>scuba_vlo, CSW0=>scuba_vhi, 
            CSW1=>scuba_vhi, CSR0=>scuba_vhi, CSR1=>scuba_vhi, 
            FULLI=>full_int, EMPTYI=>empty_int, WE=>wr_en, RE=>rd_en, 
            ORE=>rd_en, CLKW=>wr_clock, CLKR=>rd_clock, RST=>reset, 
            RPRST=>rpreset, DO0=>q(4), DO1=>q(5), DO2=>q(6), DO3=>q(7), 
            DO4=>open, DO5=>open, DO6=>open, DO7=>open, DO8=>open, 
            DO9=>open, DO10=>open, DO11=>open, DO12=>open, DO13=>open, 
            DO14=>open, DO15=>open, DO16=>open, DO17=>open, EF=>open, 
            AEF=>open, AFF=>open, FF=>open);

    async_fifo_2_5: FIFO8KB
        generic map (FULLPOINTER1=> "0b00000000000000", FULLPOINTER=> "0b11111111111100", 
        AFPOINTER1=> "0b00000000000000", AFPOINTER=> "0b11111111111100", 
        AEPOINTER1=> "0b00000000000000", AEPOINTER=> "0b11111111111100", 
        ASYNC_RESET_RELEASE=> "SYNC", GSR=> "DISABLED", RESETMODE=> "ASYNC", 
        REGMODE=> "NOREG", CSDECODE_R=> "0b11", CSDECODE_W=> "0b11", 
        DATA_WIDTH_R=>  4, DATA_WIDTH_W=>  4)
        port map (DI0=>data(8), DI1=>data(9), DI2=>data(10), 
            DI3=>data(11), DI4=>scuba_vlo, DI5=>scuba_vlo, 
            DI6=>scuba_vlo, DI7=>scuba_vlo, DI8=>scuba_vlo, 
            DI9=>scuba_vlo, DI10=>scuba_vlo, DI11=>scuba_vlo, 
            DI12=>scuba_vlo, DI13=>scuba_vlo, DI14=>scuba_vlo, 
            DI15=>scuba_vlo, DI16=>scuba_vlo, DI17=>scuba_vlo, 
            CSW0=>scuba_vhi, CSW1=>scuba_vhi, CSR0=>scuba_vhi, 
            CSR1=>scuba_vhi, FULLI=>full_int, EMPTYI=>empty_int, 
            WE=>wr_en, RE=>rd_en, ORE=>rd_en, CLKW=>wr_clock, CLKR=>rd_clock, 
            RST=>reset, RPRST=>rpreset, DO0=>q(8), DO1=>q(9), DO2=>q(10), 
            DO3=>q(11), DO4=>open, DO5=>open, DO6=>open, DO7=>open, 
            DO8=>open, DO9=>open, DO10=>open, DO11=>open, DO12=>open, 
            DO13=>open, DO14=>open, DO15=>open, DO16=>open, DO17=>open, 
            EF=>open, AEF=>open, AFF=>open, FF=>open);

    async_fifo_3_4: FIFO8KB
        generic map (FULLPOINTER1=> "0b00000000000000", FULLPOINTER=> "0b11111111111100", 
        AFPOINTER1=> "0b00000000000000", AFPOINTER=> "0b11111111111100", 
        AEPOINTER1=> "0b00000000000000", AEPOINTER=> "0b11111111111100", 
        ASYNC_RESET_RELEASE=> "SYNC", GSR=> "DISABLED", RESETMODE=> "ASYNC", 
        REGMODE=> "NOREG", CSDECODE_R=> "0b11", CSDECODE_W=> "0b11", 
        DATA_WIDTH_R=>  4, DATA_WIDTH_W=>  4)
        port map (DI0=>data(12), DI1=>data(13), DI2=>data(14), 
            DI3=>data(15), DI4=>scuba_vlo, DI5=>scuba_vlo, 
            DI6=>scuba_vlo, DI7=>scuba_vlo, DI8=>scuba_vlo, 
            DI9=>scuba_vlo, DI10=>scuba_vlo, DI11=>scuba_vlo, 
            DI12=>scuba_vlo, DI13=>scuba_vlo, DI14=>scuba_vlo, 
            DI15=>scuba_vlo, DI16=>scuba_vlo, DI17=>scuba_vlo, 
            CSW0=>scuba_vhi, CSW1=>scuba_vhi, CSR0=>scuba_vhi, 
            CSR1=>scuba_vhi, FULLI=>full_int, EMPTYI=>empty_int, 
            WE=>wr_en, RE=>rd_en, ORE=>rd_en, CLKW=>wr_clock, CLKR=>rd_clock, 
            RST=>reset, RPRST=>rpreset, DO0=>q(12), DO1=>q(13), 
            DO2=>q(14), DO3=>q(15), DO4=>open, DO5=>open, DO6=>open, 
            DO7=>open, DO8=>open, DO9=>open, DO10=>open, DO11=>open, 
            DO12=>open, DO13=>open, DO14=>open, DO15=>open, DO16=>open, 
            DO17=>open, EF=>open, AEF=>open, AFF=>open, FF=>open);

    async_fifo_4_3: FIFO8KB
        generic map (FULLPOINTER1=> "0b00000000000000", FULLPOINTER=> "0b11111111111100", 
        AFPOINTER1=> "0b00000000000000", AFPOINTER=> "0b11111111111100", 
        AEPOINTER1=> "0b00000000000000", AEPOINTER=> "0b11111111111100", 
        ASYNC_RESET_RELEASE=> "SYNC", GSR=> "DISABLED", RESETMODE=> "ASYNC", 
        REGMODE=> "NOREG", CSDECODE_R=> "0b11", CSDECODE_W=> "0b11", 
        DATA_WIDTH_R=>  4, DATA_WIDTH_W=>  4)
        port map (DI0=>data(16), DI1=>data(17), DI2=>data(18), 
            DI3=>data(19), DI4=>scuba_vlo, DI5=>scuba_vlo, 
            DI6=>scuba_vlo, DI7=>scuba_vlo, DI8=>scuba_vlo, 
            DI9=>scuba_vlo, DI10=>scuba_vlo, DI11=>scuba_vlo, 
            DI12=>scuba_vlo, DI13=>scuba_vlo, DI14=>scuba_vlo, 
            DI15=>scuba_vlo, DI16=>scuba_vlo, DI17=>scuba_vlo, 
            CSW0=>scuba_vhi, CSW1=>scuba_vhi, CSR0=>scuba_vhi, 
            CSR1=>scuba_vhi, FULLI=>full_int, EMPTYI=>empty_int, 
            WE=>wr_en, RE=>rd_en, ORE=>rd_en, CLKW=>wr_clock, CLKR=>rd_clock, 
            RST=>reset, RPRST=>rpreset, DO0=>q(16), DO1=>q(17), 
            DO2=>q(18), DO3=>q(19), DO4=>open, DO5=>open, DO6=>open, 
            DO7=>open, DO8=>open, DO9=>open, DO10=>open, DO11=>open, 
            DO12=>open, DO13=>open, DO14=>open, DO15=>open, DO16=>open, 
            DO17=>open, EF=>open, AEF=>open, AFF=>open, FF=>open);

    async_fifo_5_2: FIFO8KB
        generic map (FULLPOINTER1=> "0b00000000000000", FULLPOINTER=> "0b11111111111100", 
        AFPOINTER1=> "0b00000000000000", AFPOINTER=> "0b11111111111100", 
        AEPOINTER1=> "0b00000000000000", AEPOINTER=> "0b11111111111100", 
        ASYNC_RESET_RELEASE=> "SYNC", GSR=> "DISABLED", RESETMODE=> "ASYNC", 
        REGMODE=> "NOREG", CSDECODE_R=> "0b11", CSDECODE_W=> "0b11", 
        DATA_WIDTH_R=>  4, DATA_WIDTH_W=>  4)
        port map (DI0=>data(20), DI1=>data(21), DI2=>data(22), 
            DI3=>data(23), DI4=>scuba_vlo, DI5=>scuba_vlo, 
            DI6=>scuba_vlo, DI7=>scuba_vlo, DI8=>scuba_vlo, 
            DI9=>scuba_vlo, DI10=>scuba_vlo, DI11=>scuba_vlo, 
            DI12=>scuba_vlo, DI13=>scuba_vlo, DI14=>scuba_vlo, 
            DI15=>scuba_vlo, DI16=>scuba_vlo, DI17=>scuba_vlo, 
            CSW0=>scuba_vhi, CSW1=>scuba_vhi, CSR0=>scuba_vhi, 
            CSR1=>scuba_vhi, FULLI=>full_int, EMPTYI=>empty_int, 
            WE=>wr_en, RE=>rd_en, ORE=>rd_en, CLKW=>wr_clock, CLKR=>rd_clock, 
            RST=>reset, RPRST=>rpreset, DO0=>q(20), DO1=>q(21), 
            DO2=>q(22), DO3=>q(23), DO4=>open, DO5=>open, DO6=>open, 
            DO7=>open, DO8=>open, DO9=>open, DO10=>open, DO11=>open, 
            DO12=>open, DO13=>open, DO14=>open, DO15=>open, DO16=>open, 
            DO17=>open, EF=>open, AEF=>open, AFF=>open, FF=>open);

    async_fifo_6_1: FIFO8KB
        generic map (FULLPOINTER1=> "0b00000000000000", FULLPOINTER=> "0b11111111111100", 
        AFPOINTER1=> "0b00000000000000", AFPOINTER=> "0b11111111111100", 
        AEPOINTER1=> "0b00000000000000", AEPOINTER=> "0b11111111111100", 
        ASYNC_RESET_RELEASE=> "SYNC", GSR=> "DISABLED", RESETMODE=> "ASYNC", 
        REGMODE=> "NOREG", CSDECODE_R=> "0b11", CSDECODE_W=> "0b11", 
        DATA_WIDTH_R=>  4, DATA_WIDTH_W=>  4)
        port map (DI0=>data(24), DI1=>data(25), DI2=>data(26), 
            DI3=>data(27), DI4=>scuba_vlo, DI5=>scuba_vlo, 
            DI6=>scuba_vlo, DI7=>scuba_vlo, DI8=>scuba_vlo, 
            DI9=>scuba_vlo, DI10=>scuba_vlo, DI11=>scuba_vlo, 
            DI12=>scuba_vlo, DI13=>scuba_vlo, DI14=>scuba_vlo, 
            DI15=>scuba_vlo, DI16=>scuba_vlo, DI17=>scuba_vlo, 
            CSW0=>scuba_vhi, CSW1=>scuba_vhi, CSR0=>scuba_vhi, 
            CSR1=>scuba_vhi, FULLI=>full_int, EMPTYI=>empty_int, 
            WE=>wr_en, RE=>rd_en, ORE=>rd_en, CLKW=>wr_clock, CLKR=>rd_clock, 
            RST=>reset, RPRST=>rpreset, DO0=>q(24), DO1=>q(25), 
            DO2=>q(26), DO3=>q(27), DO4=>open, DO5=>open, DO6=>open, 
            DO7=>open, DO8=>open, DO9=>open, DO10=>open, DO11=>open, 
            DO12=>open, DO13=>open, DO14=>open, DO15=>open, DO16=>open, 
            DO17=>open, EF=>open, AEF=>open, AFF=>open, FF=>open);

    scuba_vhi_inst: VHI
        port map (Z=>scuba_vhi);

    scuba_vlo_inst: VLO
        port map (Z=>scuba_vlo);

    async_fifo_7_0: FIFO8KB
        generic map (FULLPOINTER1=> "0b00000000000000", FULLPOINTER=> "0b11111111111100", 
        AFPOINTER1=> "0b00000000000000", AFPOINTER=> "0b11111111111100", 
        AEPOINTER1=> "0b00000000000000", AEPOINTER=> "0b11111111111100", 
        ASYNC_RESET_RELEASE=> "SYNC", GSR=> "DISABLED", RESETMODE=> "ASYNC", 
        REGMODE=> "NOREG", CSDECODE_R=> "0b11", CSDECODE_W=> "0b11", 
        DATA_WIDTH_R=>  4, DATA_WIDTH_W=>  4)
        port map (DI0=>data(28), DI1=>data(29), DI2=>data(30), 
            DI3=>data(31), DI4=>scuba_vlo, DI5=>scuba_vlo, 
            DI6=>scuba_vlo, DI7=>scuba_vlo, DI8=>scuba_vlo, 
            DI9=>scuba_vlo, DI10=>scuba_vlo, DI11=>scuba_vlo, 
            DI12=>scuba_vlo, DI13=>scuba_vlo, DI14=>scuba_vlo, 
            DI15=>scuba_vlo, DI16=>scuba_vlo, DI17=>scuba_vlo, 
            CSW0=>scuba_vhi, CSW1=>scuba_vhi, CSR0=>scuba_vhi, 
            CSR1=>scuba_vhi, FULLI=>full_int, EMPTYI=>empty_int, 
            WE=>wr_en, RE=>rd_en, ORE=>rd_en, CLKW=>wr_clock, CLKR=>rd_clock, 
            RST=>reset, RPRST=>rpreset, DO0=>q(28), DO1=>q(29), 
            DO2=>q(30), DO3=>q(31), DO4=>open, DO5=>open, DO6=>open, 
            DO7=>open, DO8=>open, DO9=>open, DO10=>open, DO11=>open, 
            DO12=>open, DO13=>open, DO14=>open, DO15=>open, DO16=>open, 
            DO17=>open, EF=>open, AEF=>open, AFF=>open, FF=>open);

    empty <= empty_int;
    full <= full_int;
end Structure;

-- synopsys translate_off
library MACHXO2;
configuration Structure_CON of async_fifo is
    for Structure
        for all:VHI use entity MACHXO2.VHI(V); end for;
        for all:VLO use entity MACHXO2.VLO(V); end for;
        for all:FIFO8KB use entity MACHXO2.FIFO8KB(V); end for;
    end for;
end Structure_CON;

-- synopsys translate_on
