create_clock -period 20.000 -name ps_clk -waveform {0.000 10.000} [get_pins */PS7_inst/FCLKCLK[0]]

# North Plugin Slot
# set_property PACKAGE_PIN U7  [get_ports  "CLK_LANE_P"]
# set_property PACKAGE_PIN V7  [get_ports  "CLK_LANE_N"]
# set_property PACKAGE_PIN T17 [get_ports  "DATA_LANE_0_P"]
# set_property PACKAGE_PIN R18 [get_ports  "DATA_LANE_0_N"]
# set_property PACKAGE_PIN W18 [get_ports  "DATA_LANE_1_P"]
# set_property PACKAGE_PIN W19 [get_ports  "DATA_LANE_1_N"]
# set_property PACKAGE_PIN P15 [get_ports  "DATA_LANE_2_P"]
# set_property PACKAGE_PIN P16 [get_ports  "DATA_LANE_2_N"]
# set_property PACKAGE_PIN T5 [get_ports  "DATA_LANE_3_P"]
# set_property PACKAGE_PIN U5 [get_ports  "DATA_LANE_3_N"]
# set_property PACKAGE_PIN V8 [get_ports  "DATA_LANE_4_P"]
# set_property PACKAGE_PIN W8 [get_ports  "DATA_LANE_4_N"]

# South Plugin Slot
set_property PACKAGE_PIN K14 [get_ports  "CLK_LANE_P"]
set_property PACKAGE_PIN J14 [get_ports  "CLK_LANE_N"]
set_property PACKAGE_PIN V11 [get_ports  "DATA_LANE_0_P"]
set_property PACKAGE_PIN V10 [get_ports  "DATA_LANE_0_N"]
set_property PACKAGE_PIN Y12 [get_ports  "DATA_LANE_1_P"]
set_property PACKAGE_PIN Y13 [get_ports  "DATA_LANE_1_N"]
set_property PACKAGE_PIN V6  [get_ports  "DATA_LANE_2_P"]
set_property PACKAGE_PIN W6  [get_ports  "DATA_LANE_2_N"]
set_property PACKAGE_PIN M14 [get_ports  "DATA_LANE_3_P"]
set_property PACKAGE_PIN M15 [get_ports  "DATA_LANE_3_N"]
set_property PACKAGE_PIN N15 [get_ports  "DATA_LANE_4_P"]
set_property PACKAGE_PIN N16 [get_ports  "DATA_LANE_4_N"]

set_property IOSTANDARD LVDS_25  [get_ports {DATA_LANE_*}]
set_property IOSTANDARD LVDS_25  [get_ports {CLK_LANE_*}]

# SCL/ICSP Clock	JX2_SE_0[G14]
set_property PACKAGE_PIN G14 [get_ports I2C_SCL]
set_property IOSTANDARD LVCMOS25 [get_ports I2C_SCL]
set_property SLEW SLOW [get_ports I2C_SCL]
set_property DRIVE 12 [get_ports I2C_SCL]

# SDA/ICSP Data		JX2_SE_1[J15]
set_property PACKAGE_PIN J15 [get_ports I2C_SDA]
set_property IOSTANDARD LVCMOS25 [get_ports I2C_SDA]
set_property SLEW SLOW [get_ports I2C_SDA]
set_property DRIVE 12 [get_ports I2C_SDA]
