[ActiveSupport PAR]
; Global primary clocks
GLOBAL_PRIMARY_USED = 2;
; Global primary clock #0
GLOBAL_PRIMARY_0_SIGNALNAME = sclk;
GLOBAL_PRIMARY_0_DRIVERTYPE = CLKDIV;
GLOBAL_PRIMARY_0_LOADNUM = 239;
; Global primary clock #1
GLOBAL_PRIMARY_1_SIGNALNAME = clk_int;
GLOBAL_PRIMARY_1_DRIVERTYPE = OSC;
GLOBAL_PRIMARY_1_LOADNUM = 12;
; # of global secondary clocks
GLOBAL_SECONDARY_USED = 8;
; Global secondary clock #0
GLOBAL_SECONDARY_0_SIGNALNAME = sclk_enable_230;
GLOBAL_SECONDARY_0_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_0_LOADNUM = 65;
GLOBAL_SECONDARY_0_SIGTYPE = CE;
; Global secondary clock #1
GLOBAL_SECONDARY_1_SIGNALNAME = n8375;
GLOBAL_SECONDARY_1_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_1_LOADNUM = 26;
GLOBAL_SECONDARY_1_SIGTYPE = RST;
; Global secondary clock #2
GLOBAL_SECONDARY_2_SIGNALNAME = n8376;
GLOBAL_SECONDARY_2_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_2_LOADNUM = 26;
GLOBAL_SECONDARY_2_SIGTYPE = RST;
; Global secondary clock #3
GLOBAL_SECONDARY_3_SIGNALNAME = sclk_enable_104;
GLOBAL_SECONDARY_3_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_3_LOADNUM = 16;
GLOBAL_SECONDARY_3_SIGTYPE = CE;
; Global secondary clock #4
GLOBAL_SECONDARY_4_SIGNALNAME = FT601_CLK_c;
GLOBAL_SECONDARY_4_DRIVERTYPE = CLK_PIN;
GLOBAL_SECONDARY_4_LOADNUM = 9;
GLOBAL_SECONDARY_4_SIGTYPE = CLK;
; Global secondary clock #5
GLOBAL_SECONDARY_5_SIGNALNAME = rx_rdy;
GLOBAL_SECONDARY_5_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_5_LOADNUM = 51;
GLOBAL_SECONDARY_5_SIGTYPE = RST;
; Global secondary clock #6
GLOBAL_SECONDARY_6_SIGNALNAME = sclk_enable_231;
GLOBAL_SECONDARY_6_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_6_LOADNUM = 35;
GLOBAL_SECONDARY_6_SIGTYPE = CE;
; Global secondary clock #7
GLOBAL_SECONDARY_7_SIGNALNAME = deser_inst/n3741;
GLOBAL_SECONDARY_7_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_7_LOADNUM = 25;
GLOBAL_SECONDARY_7_SIGTYPE = RST;
; Edge Clocks
EDGE_USED = 1;
; Edge clock #0
EDGE_0_SIGNALNAME = deser_inst/ddrx4_inst/eclko;
EDGE_0_DRIVERTYPE = CLK_PIN;
EDGE_0_LOADNUM = 6;
; I/O Bank 0 Usage
BANK_0_USED = 10;
BANK_0_AVAIL = 19;
BANK_0_VCCIO = 2.5V;
BANK_0_VREF1 = NA;
; I/O Bank 1 Usage
BANK_1_USED = 18;
BANK_1_AVAIL = 21;
BANK_1_VCCIO = 2.5V;
BANK_1_VREF1 = NA;
; I/O Bank 2 Usage
BANK_2_USED = 12;
BANK_2_AVAIL = 20;
BANK_2_VCCIO = 2.5V;
BANK_2_VREF1 = NA;
; I/O Bank 3 Usage
BANK_3_USED = 6;
BANK_3_AVAIL = 6;
BANK_3_VCCIO = 2.5V;
BANK_3_VREF1 = NA;
; I/O Bank 4 Usage
BANK_4_USED = 5;
BANK_4_AVAIL = 6;
BANK_4_VCCIO = 2.5V;
BANK_4_VREF1 = NA;
; I/O Bank 5 Usage
BANK_5_USED = 5;
BANK_5_AVAIL = 8;
BANK_5_VCCIO = 2.5V;
BANK_5_VREF1 = NA;
